companieshouse/your-companies-web

README.md

README file updated with a text relevant to this web service

IDVA6-372 Readme updated

---

package-lock.json
package.json
src/app.ts
src/constants.ts
src/lib/utils/environmentValue.ts
src/middleware/authentication.middleware.ts
src/middleware/company.authentication.ts
src/middleware/session.middleware.ts
test/mocks/all.middleware.mock.ts
test/mocks/authentication.middleware.mock.ts
test/mocks/session.middleware.mock.ts
test/src/routers/yourCompaniesRouter.test.ts
test/src/setup.ts

Link to Jira ticket:
https://companieshouse.atlassian.net/browse/IDVA6-453
Changes:
Cookie-based session middleware (node-session-handler and redis) and user authentication (web-security-node)
is applied to all routes which follow the pattern - /your-companies*

Feature/ida6 453 User authentication and session handling

---

Makefile
Tiltfile.dev
gulpfile.js
src/app.ts
src/lib/utils/sessionUtils.ts
src/routers/handlers/yourCompanies/yourCompanies.ts
src/views/layouts/default.njk
src/views/partials/__footer.njk
src/views/partials/__meta_header.njk
src/views/partials/customer_insights.njk
src/views/partials/nav/top.njk
start.sh
test/mocks/session.mock.ts
test/src/lib/utils/sessionUtils.test.ts
test/src/routers/yourCompaniesRouter.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-454
Changes:
- Footer content updated
- Navbar hrefs updated
- Stylesheet linking updated
- User email retrieved from session and displayed in the navbar
- Files required to build and start app added/modified

IDVA6-454 adding static content

---

package-lock.json
sonar-project.properties

Caniuse-lite version updated

---

src/constants.ts
src/locales/cy/translation/add-company.json
src/locales/en/translation/add-company.json
src/routers/handlers/yourCompanies/addCompany.ts
src/views/router_views/your_companies/add_company.njk
test/src/routers/yourCompaniesRouter.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-503
Changes:
- Additional error message added for scenario when no company number provided
- Tests updated and new added

IDVA6-503 error message on enter company details page

---

package.json
sonar-project.properties

Updated scripts to run SonarQube tests on pull requests

Updated scripts to run SonarQube tests on pull requests

---

sonar-project.properties

SonarQube inclusions path updated

SonarQube inclusions path updated

---

src/constants.ts
src/locales/cy/translation/common.json
src/locales/cy/translation/your-companies.json
src/locales/en/translation/common.json
src/locales/en/translation/your-companies.json
src/routers/controllers/addPresenterController.ts
src/routers/handlers/genericHandler.ts
src/routers/handlers/yourCompanies/yourCompaniesHandler.ts
src/services/userCompanyAssociationService.ts
src/types/associations.ts
src/views/user-invitations-banner.njk
src/views/your-companies.njk
test/mocks/associations.mock.ts
test/src/routers/controllers/yourCompaniesController.addCompany.test.ts
test/src/routers/controllers/yourCompaniesController.test.ts
test/src/services/userCompanyAssociationService.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-531
Changes:
- Invitations banner added to your companies page
- Fixes to various issues flagged by SonarQube
- Add company tests separated to their own file

IDVA6-531 accept and decline view invitation banner page

---

src/locales/cy/translation/company-invitations-accept.json
src/locales/en/translation/company-invitations-accept.json

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-533
Changes:
- Missing title added

IDVA6-533 Missing title added

---

src/locales/cy/translation/company-invitations-decline.json
src/locales/en/translation/company-invitations-decline.json
src/routers/controllers/companyInvitationsDeclineController.ts
src/routers/handlers/yourCompanies/companyInvitationsDeclineHandler.ts
src/routers/handlers/yourCompanies/companyInvitationsHandler.ts
src/routers/router.ts
src/views/company-invitations-decline.njk
src/views/macros/link.njk
test/src/routers/controllers/companyInvitationsDeclineController.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-534
Changes:
- Declined invitation success page creation
- Created unit tests for declined invitation page

IDVA6-534 declined invitation success page

---

src/locales/cy/translation/add-presenter-check-details.json
src/locales/cy/translation/add-presenter.json
src/locales/en/translation/add-presenter-check-details.json
src/locales/en/translation/add-presenter.json

Minor text updates
Links to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-671
https://companieshouse.atlassian.net/browse/IDVA6-670

IDVA6-670 and 671 - content wording updates

---

src/views/add-presenter.njk

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-697
Changes:
Adds a novalidate attribute to the form, removing the browser validation behaviour for email inputs

IDVA6-697 Remove automatic browser email validation

---

package.json
src/constants.ts
src/lib/helpers/buildPaginationHelper.ts
src/lib/validation/generic.ts
src/locales/cy/translation/your-companies.json
src/locales/en/translation/your-companies.json
src/routers/controllers/yourCompaniesController.ts
src/routers/handlers/yourCompanies/yourCompaniesHandler.ts
src/routers/router.ts
src/services/associationsService.ts
src/types/pagination.ts
src/views/macros/link.njk
src/views/previously-added-companies.njk
src/views/your-companies.njk
test/mocks/associations.mock.ts
test/src/lib/helpers/buildPaginationHelper.test.ts
test/src/lib/validation/generic.test.ts
test/src/routers/controllers/yourCompaniesController.paginationContent.test.ts
test/src/routers/controllers/yourCompaniesController.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-559
Changes:
- private-api-sdk-node package updated
- search and pagination feature added
- validation for the company number search added

IDVA6-559 api integration your companies page

---

src/constants.ts
src/locales/cy/translation/your-companies.json
src/locales/en/translation/your-companies.json
src/routers/controllers/yourCompaniesController.ts
src/routers/handlers/yourCompanies/yourCompaniesHandler.ts
src/views/previously-added-companies.njk
src/views/your-companies.njk
test/src/lib/helpers/buildPaginationHelper.test.ts
test/src/middleware/company.authentication.middleware.test.ts
test/src/routers/controllers/yourCompaniesController.paginationContent.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-802
Changes:
- The hint text for a search input field updated.
- Search input validation and error messages added
- Unnecessary imports and unused variable removed

IDVA6-802 your companies search error message

---

src/routers/handlers/yourCompanies/addPresenterHandler.ts
src/routers/handlers/yourCompanies/checkPresenterHandler.ts
test/src/routers/controllers/addPresenterController.test.ts
test/src/routers/controllers/checkPresenterController.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-901
Changes:
- Unnecessary calls to company profile service removed
- Tests updated

IDVA6-901 api integration get company profile

---

src/constants.ts
src/routerDispatch.ts
src/routers/controllers/checkPresenterController.ts
src/routers/controllers/personNotAdded.ts
src/routers/controllers/resendEmailController.ts
src/routers/handlers/yourCompanies/checkPresenterHandler.ts
src/routers/router.ts
src/views/partials/error_404.njk
test/src/routers/controllers/personNotAdded.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-561
Changes:
- Code refactored to tackle 400 response from the API
- A controller added for the future page for a person not added

IDVA6-561 api integration check email address is correct

---

src/app.ts
src/routers/controllers/httpErrorController.ts
src/services/associationsService.ts
test/src/routers/controllers/createCompanyAssociationController.test.ts
test/src/routers/controllers/httpErrorController.test.ts
test/src/services/associationsService.createAssociation.test.ts
test/src/services/associationsService.updateAssociationStatus.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-929
Changes:
Api error handling and logging added for the creating and updating association requests.

IDVA6 929 Handle api errors

---

src/locales/cy/translation/your-companies.json
src/locales/en/translation/your-companies.json
src/routers/handlers/yourCompanies/yourCompaniesHandler.ts
src/views/previously-added-companies.njk

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-922
Changes:
- Cancel search link added

IDVA6-922 Cancel search link added

---

src/constants.ts
src/lib/helpers/invitationHelper.ts
src/lib/utils/date.ts
src/routers/handlers/yourCompanies/manageAuthorisedPeopleHandler.ts
test/mocks/associations.mock.ts
test/src/lib/helpers/invitationHelper.test.ts
test/src/lib/utils/date.test.ts
test/src/routers/controllers/manageAuthorisedPeopleController.confirmationPersonRemoved.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-938
Changes:
- Additional logic added to display associations with valid invitations

IDVA6-938 expired invitations in people digitally authorised page

---

src/lib/utils/referrerUtils.ts
src/middleware/company.authentication.ts
src/middleware/navigation/addPresenter.middleware.ts
src/middleware/navigation/cancelPerson.middleware.ts
src/middleware/navigation/checkPresenter.middleware.ts
src/middleware/navigation/companyAdded.middleware.ts
src/middleware/navigation/companyInvitationsAccept.middleware.ts
src/middleware/navigation/companyInvitationsDecline.middleware.ts
src/middleware/navigation/confirmCompany.middleware.ts
src/middleware/navigation/manageAuthorisedPeople.middleware.ts
src/middleware/navigation/removeAuthorisedPerson.middleware.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-973
Changes:
Adding logging for bookmark redirection functions

IDVA6-973 Add logging for redirect middleware functions

---

src/constants.ts
src/routers/handlers/yourCompanies/companyInvitationsHandler.ts
src/services/associationsService.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-963
Changes:
- Adding additional parameter to getUserAssociations
- Updating .searchAssociations with itemsPerPage parameter

IDVA6-963 - updating getUserAssociations function to allow more than 15 invitations

---

src/constants.ts
src/routers/controllers/companyInvitationsAcceptController.ts
src/routers/controllers/companyInvitationsDeclineController.ts
src/routers/handlers/yourCompanies/companyInvitationsAcceptHandler.ts
src/routers/handlers/yourCompanies/companyInvitationsDeclineHandler.ts
src/views/company-invitations.njk
test/src/routers/controllers/companyInvitationsAcceptController.test.ts
test/src/routers/controllers/companyInvitationsDeclineController.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-964
Changes:
- Script added to reload a page to ensure only the valid invitations are displayed
- Additional logic added to prevent accepting and declining the same invitation

IDVA6-964 prevent accepting and declining the same invitation

---

src/app.ts
src/views/partials/__meta_header.njk
src/views/partials/matomo-script.njk

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-848
Changes:
- Matomo main script and configuration added

IDVA6-848 Matomo main script and configuration

---

src/constants.ts
src/routers/handlers/yourCompanies/addCompanyHandler.ts
src/routers/handlers/yourCompanies/companyAddSuccessHandler.ts
src/routers/handlers/yourCompanies/confirmCorrectCompanyHandler.ts
src/routers/handlers/yourCompanies/yourCompaniesHandler.ts
src/views/add-company.njk
src/views/confirm-company-details.njk
src/views/confirmation-company-added.njk
src/views/macros/link.njk
src/views/manage-authorised-people.njk
src/views/no-companies-added.njk
src/views/previously-added-companies.njk

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-848
Changes:
- Matomo tags added to buttons and links on pages of the add company journey
- Code refactored to make it more readable
- Link macro modified to incorporate Matomo tags

IDVA6-848 analytics add company

---

src/constants.ts
src/routers/handlers/yourCompanies/manageAuthorisedPeopleHandler.ts
src/views/manage-authorised-people.njk

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-850
Changes:
- Matomo analytics functionality added for 'Add authorised user' button and 'Remove', 'Cancel' and 'Resend email' links

IDVA6-850 - analytics people digitally authorised to file

---

src/lib/utils/referrerUtils.ts
src/routers/controllers/httpErrorController.ts
test/src/lib/utils/referrerUtils.test.ts

Link to Jira:
IDVA6-973](https://companieshouse.atlassian.net/browse/IDVA6-973
Changes:
Updates navigation function to always allow entry when the pageIndicator is true.

IDVA6 793 Cancel / Remove fix - navigation check update

---

src/constants.ts
src/routers/handlers/yourCompanies/manageAuthorisedPeopleHandler.ts
src/routers/handlers/yourCompanies/removeAuthorisedPersonHandler.ts
src/views/manage-authorised-people.njk
src/views/remove-authorised-person.njk

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-853
Changes:
- Matomo tags added to remove authorised person page

IDVA6-853 Analytics - Remove an authorised person

---

src/routers/handlers/yourCompanies/cancelPersonHandler.ts
src/views/cancel-person.njk

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-855
Changes:
- Matomo tags added to cancel person page

IDVA6-855 analytics cancel an authorised person

---

src/routers/handlers/yourCompanies/manageAuthorisedPeopleHandler.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1055
Changes:
- Fix to a problem with errors displayed when they should not be

IDVA6-1055 Old error message appearing on fresh page

---

src/locales/cy/translation/company-invitations.json
src/locales/en/translation/company-invitations.json
src/views/company-invitations.njk
test/src/routers/controllers/companyInvitationsController.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-692
Changes:
- Info displayed instead of a table if no pending invitations exist

IDVA6-692 invitations to be digitally authorised no invitation

---

src/app.ts
src/constants.ts
src/routers/handlers/yourCompanies/cancelPersonHandler.ts
src/routers/handlers/yourCompanies/checkPresenterHandler.ts
src/routers/handlers/yourCompanies/companyAddSuccessHandler.ts
src/routers/handlers/yourCompanies/companyInvitationsAcceptHandler.ts
src/routers/handlers/yourCompanies/companyInvitationsDeclineHandler.ts
src/routers/handlers/yourCompanies/companyInvitationsHandler.ts
src/routers/handlers/yourCompanies/confirmCorrectCompanyHandler.ts
src/routers/handlers/yourCompanies/manageAuthorisedPeopleHandler.ts
src/routers/handlers/yourCompanies/removeAuthorisedPersonHandler.ts
src/routers/handlers/yourCompanies/yourCompaniesHandler.ts
src/types/invitations.ts
src/views/company-invitations-accept.njk
src/views/company-invitations-decline.njk
src/views/company-invitations.njk

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-852
Changes:
- Added interface 'Invitations' to return an object in companyInvitationsHandler
- Added analytics functionality for accept and decline links on invitations page
- Added analytics functionality for 'View your companies' buttons on accept/decline confirmation pages

IDVA6-852 - analytics - authenticated user invitations pages

---

src/constants.ts
src/routers/handlers/yourCompanies/manageAuthorisedPeopleHandler.ts
src/routers/handlers/yourCompanies/yourCompaniesHandler.ts
src/views/manage-authorised-people.njk
src/views/no-companies-added.njk
src/views/partials/matomo-script.njk
src/views/previously-added-companies.njk

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1033
Changes:
- Goal tracking script added
- Goal tracking added to Add a company and Add new authorised person buttons added

IDVA6-1033 add goals to journeys

---

src/lib/utils/referrerUtils.ts

Changes:
- Adding documentation for redirectPage function in referrerUtils.ts

Documentation for redirectPage function

---

src/views/partials/__footer.njk
src/views/partials/__meta_header.njk
src/views/partials/__styles.njk

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1046
Changes:
- Double slash added in front of cdn host

IDVA6-1046 Footer - Crown Copyright logo missing on Phoenix

---

src/views/partials/__footer.njk
src/views/partials/__meta_header.njk
src/views/partials/__styles.njk

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1046
Changes:
- Reverted addition of double slashes in front of cdn host

IDVA6-1046 Footer - Crown Copyright logo missing on Phoenix (2)

---

src/constants.ts
src/routers/handlers/yourCompanies/yourCompaniesHandler.ts
src/views/previously-added-companies.njk

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-849
Changes:
Matomo tags for search button, cancel search, no results found and errors.

IDVA6-849 - Analytics - Multiple companies

---

src/views/partials/customer_insights.njk

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1007
Changes:
- Href in a link to survey changed
- Onclick event in a link fixed

IDVA6-1007 footer - tell us what you think of this service link

---

src/app.ts
src/constants.ts
src/views/partials/__footer.njk
src/views/partials/matomo-script.njk

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1058
Changes:
- Piwik cookie consent script replaced with relevant Matomo script
- Matomo start script modified to trigger only on cookie consent

IDVA6-1058 fix problem with bind piwik listener not being defined

---

assets/src/scss/__global.scss

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1086
Changes:
- Changes to prevent a link to move outside the main content box when zoom 250%

IDVA6-1086 Zoomed in footer layout

---

assets/src/scss/__global.scss
src/views/previously-added-companies.njk

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1101
Changes:
- A wrapper div adde to modify behaviour or the included elements
- Additional styles added

IDVA6-1101 mobile view layout issues search section

---

src/constants.ts
src/routers/handlers/yourCompanies/presenterAlreadyAddedHandler.ts
src/views/presenter-already-added.njk

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-931
Changes:
- Added global 'Back Link' variable for matomo
- Added matomo tracking for back link and 'Back to Your Companies' link
- Updated back_link.njk to contain id for matomo tracking

IDVA6-931 - matomo functionality for presenterAlreadyAuthorised page

---

assets/src/scss/__global.scss
src/views/add-company.njk
src/views/add-presenter-check-details.njk

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1110
Changes:
- Stylings added to fix mobile view issues

IDVA6-1110 Mobile view layout issue

---

src/locales/cy/translation/common.json
src/locales/en/translation/common.json
src/views/partials/__footer.njk
src/views/partials/__meta_header.njk
src/views/partials/nav/top.njk

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1102
Changes:
- Script and stylesheet to fix the menu in mobile mode added

IDVA6-1102 Nav bar for mobile view fixed

---

assets/src/scss/__global.scss
src/views/add-presenter-check-details.njk

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1110
Changes:
- Different CSS classes used for the element styling

IDVA6-1110 Problem with margin in mobile view fixed

---

src/lib/utils/referrerUtils.ts
src/middleware/navigation/addPresenter.middleware.ts
src/middleware/navigation/cancelPerson.middleware.ts
src/middleware/navigation/checkPresenter.middleware.ts
src/middleware/navigation/companyInvitationsAccept.middleware.ts
src/middleware/navigation/companyInvitationsDecline.middleware.ts
src/middleware/navigation/confirmCompany.middleware.ts
src/middleware/navigation/manageAuthorisedPeople.middleware.ts
src/middleware/navigation/personRemovedThemselves.middleware.ts
src/middleware/navigation/presenterAlreadyAdded.middleware.ts
src/middleware/navigation/removeAuthorisedPerson.middleware.ts
src/routers/handlers/yourCompanies/yourCompaniesHandler.ts
src/routers/router.ts
test/src/routers/controllers/cancelPersonController.test.ts
test/src/routers/controllers/manageAuthorisedPeopleController.authorisationEmailResent.test.ts
test/src/routers/controllers/removeAuthorisedPersonController.test.ts
test/src/routers/controllers/removeThemselvesConfirmationController.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1057
Changes:
- Added redirect functionality for resend email confirmation page
- Updated redirect function to allow for changing languages on person already added page
- Added redirect functionality and unit tests for userRemovedThemselves page

IDVA6-1057 - redirect bookmarked pages

---

src/constants.ts
src/routers/handlers/yourCompanies/removeThemselvesConfirmationHandler.ts
src/views/confirmation-person-removed-themselves.njk

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1053
Changes:
- Added analytics for 'Go to Your Companies' button on page

IDVA6-1053 - analytics - user removed themself

---

package-lock.json
package.json
src/views/previously-added-companies.njk

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1141
Changes:
- trackEvent calls for the button and link related to search made optional
- Vulnerabilities in dependencies fixed

IDVA6-1141 TypeError: Cannot read properties of null (reading 'addEventListener')

---

assets/src/scss/__global.scss
src/views/partials/__meta_header.njk

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1153
Changes:
- Unnecessary font-face removed
- Unnecessary link to govuk-frontend css file removed

IDVA6-1153 fix flickering issue

---

assets/src/scss/__global.scss

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1153
Changes:
- Custom function creating path to fonts added

IDVA6-1153 Custom function creating path to fonts added

---

src/routers/handlers/yourCompanies/companyInvitationsHandler.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-427
Changes:
- Variable name fixed

IDVA6-427 Variable name fixed

---

src/routers/controllers/manageAuthorisedPeopleController.ts
src/routers/handlers/yourCompanies/manageAuthorisedPeopleHandler.ts
test/src/routers/controllers/manageAuthorisedPeopleController.authorisationEmailResent.test.ts
test/src/routers/controllers/manageAuthorisedPeopleController.confirmationCancelPerson.test.ts
test/src/routers/controllers/manageAuthorisedPeopleController.confirmationPersonAdded.test.ts
test/src/routers/controllers/manageAuthorisedPeopleController.confirmationPersonRemoved.test.ts
test/src/routers/controllers/manageAuthorisedPeopleController.pagination.test.ts
test/src/routers/controllers/manageAuthorisedPeopleController.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1201
Changes:
- A check added to prevent unauthorised access to manage authorised people page
- Tests updated and new added

IDVA6-1201 prevent unauthorised access to manage authorised people page

---

src/constants.ts
src/lib/utils/referrerUtils.ts
src/middleware/navigation/addPresenter.middleware.ts
src/middleware/navigation/cancelPerson.middleware.ts
src/middleware/navigation/checkPresenter.middleware.ts
src/middleware/navigation/companyInvitationsAccept.middleware.ts
src/middleware/navigation/companyInvitationsDecline.middleware.ts
src/middleware/navigation/confirmCompany.middleware.ts
src/middleware/navigation/manageAuthorisedPeople.middleware.ts
src/middleware/navigation/personRemovedThemselves.middleware.ts
src/middleware/navigation/presenterAlreadyAdded.middleware.ts
src/middleware/navigation/removeAuthorisedPerson.middleware.ts
src/routers/controllers/cancelPersonController.ts
src/routers/controllers/confirmCompanyController.ts
src/routers/controllers/manageAuthorisedPeopleController.ts
src/routers/controllers/removeAuthorisedPersonController.ts
src/routers/handlers/yourCompanies/manageAuthorisedPeopleHandler.ts
src/routers/handlers/yourCompanies/yourCompaniesHandler.ts
test/src/routers/controllers/cancelPersonController.test.ts
test/src/routers/controllers/removeAuthorisedPersonController.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1176
Changes:
- Added emailArray for managed authorised people page to redirect any user email not on page
- Updated manage authorised people page indicator to include companyNumber

IDVA6-1176 - bug fix - remove and cancel user page redirecting

---

src/constants.ts
src/routers/controllers/createCompanyAssociationController.ts
src/routers/handlers/yourCompanies/addCompanyHandler.ts
test/src/routers/controllers/createCompanyAssociationController.test.ts

Jira
https://companieshouse.atlassian.net/browse/IDVA6-1204
Changes patch requests to post requests for the add a company (search company number journey). We now no longer make patch requests to /associations/{id} in the createCompanyAssociationController.

IDVA6-1204 remove patch requests from createCompanyAssociationController

---

package-lock.json
package.json
src/middleware/navigation/manageAuthorisedPeople.middleware.ts
src/routers/controllers/removeAuthorisedPersonRequestController.ts
src/routers/handlers/yourCompanies/manageAuthorisedPeopleHandler.ts
src/services/associationsService.ts
test/src/routers/controllers/manageAuthorisedPeopleController.confirmationCancelPerson.test.ts
test/src/routers/controllers/removeAuthorisedPersonRequestController.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1229
Changes:
Removal of association
- updates verification request to handle pagination
- typo fixed
Cancellation of association
- updates request to handle pagination
- add missing await operator to removeUserFromCompanyAssocations
Navigation checks
- resend email url now includes formatted company number in url
- adds an allow list for the resend email confirmation page

IDAV6 1229 Fixes for manage authorised people page

---

src/views/company-invitations.njk

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1224
Changes:
- Updated title variable in trackEvent function call on invitations page

IDVA6-1224 - Bug Fix - Matomo events not triggering on invitations page

---

assets/src/scss/__global.scss
src/views/partials/__footer.njk

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1259
Changes:
- Footer css issues fixed

IDVA6-1259 Footer css issues

---

assets/src/scss/__global.scss
src/views/partials/__header.njk

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1006
Changes:
- Added redesigned header code from 1005
- Added 'does not verify' link
- Added new styling to add spacing to reflect prototype

IDVA6-1006 - Header - Companies House does not verify accuracy link

---

README.md

Link to Jira: 
https://companieshouse.atlassian.net/browse/IDVA6-528
Changes:
- Update to the 'Running the app' section, adding instructions on how to run the app with docker.

IDVA6-528 running the app section updated

---

src/app.ts
src/constants.ts
src/locales/cy/translation/service-unavailable.json
src/locales/en/translation/service-unavailable.json
src/routerDispatch.ts
src/routers/controllers/httpErrorController.ts
src/views/layouts/shell.njk
src/views/partials/service_unavailable.njk
test/src/routers/controllers/httpErrorController.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1235
Changes:
Fixes accessibility issues with the Service Unavailable (error) page.

IDVA6-1235 Bug fix for service unavailable page - IDVA6-338

---

README.md

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1288
Changes:
- Empty commit to trigger a re-build - investigating, resolve build / versioning issues.

IDVA6-1288 empty commit that will trigger a rebuild

---

assets/src/scss/__global.scss
src/views/partials/__header.njk

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1286
Changes:
- Modifying styles to fix banner issue on Safari

IDVA6-1286 - Bug fix - banner not displaying correctly on Safari

---

src/routers/handlers/yourCompanies/manageAuthorisedPeopleHandler.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1292
Changes:
- Data filtering removed due to moving this functionality to the backend

IDVA6-1292 Pagination showing for 15 or less users

---

src/constants.ts
src/routers/handlers/yourCompanies/companyInvitationsHandler.ts
src/routers/handlers/yourCompanies/yourCompaniesHandler.ts
src/views/company-invitations.njk
src/views/your-companies.njk

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1223
Changes:
- Updated back link analytics on invitations page
- Added analytics functionality to your companies invitations link

IDVA6-1223 - Analytics - View invitations to be digitally authorised link

---

src/routers/handlers/yourCompanies/manageAuthorisedPeopleHandler.ts
src/views/company-invitations.njk
src/views/manage-authorised-people.njk
test/src/routers/controllers/manageAuthorisedPeopleController.confirmationCancelPerson.test.ts
test/src/routers/controllers/manageAuthorisedPeopleController.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1346
Changes:
- Updated back link content on invitations page and manage authorised people page
- Updated relevant unit tests
- Updated matomo tags on back links for these pages

IDVA6-1346 - Content Update - Update back to your companies content

---

src/locales/cy/translation/add-company.json
src/locales/cy/translation/common.json
src/locales/cy/translation/confirm-company-details.json
src/locales/cy/translation/confirmation-company-added.json

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1299
Changes:
- Added Welsh translations for 'add company' page
- Updated 'continue' translation in common.json

IDVA6-1299 - Welsh Translation - Add a Company

---

src/locales/cy/translation/add-company.json
src/locales/cy/translation/add-presenter.json
src/locales/cy/translation/cancel-person.json
src/locales/cy/translation/common.json
src/locales/cy/translation/remove-authorised-person.json
src/locales/cy/translation/your-companies.json

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1300
Changes:
- Added Welsh error translations to language files

IDVA6-1300 - Welsh Translation - Error Messages

---

src/constants.ts
src/middleware/navigation/companyInvitationsAccept.middleware.ts
src/middleware/navigation/companyInvitationsDecline.middleware.ts
src/middleware/navigation/confirmCompany.middleware.ts
src/routers/handlers/yourCompanies/addCompanyHandler.ts
src/routers/handlers/yourCompanies/companyInvitationsAcceptHandler.ts
src/routers/handlers/yourCompanies/companyInvitationsDeclineHandler.ts
src/routers/handlers/yourCompanies/yourCompaniesHandler.ts
test/src/routers/controllers/companyInvitationsAcceptController.test.ts
test/src/routers/controllers/companyInvitationsDeclineController.test.ts
test/src/routers/controllers/yourCompaniesController.addCompany.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1384
Changes:
- Updated accept/decline invitation url to function with apostrophes in company name
- Added referrer url functionality to detect if user has changed the language on the page to prevent redirection to previous page

IDVA6-1384 - Bug Fix - Navigating to previous page when changing languages

---

src/middleware/i18next.language.ts

- Try loading from local environment, if fails, then try loading from external environment
- If external environment loading fails, the error will bubble up to the top and we'll need to check the failure

BAU: Fix reading from local/external env

---

src/routers/handlers/yourCompanies/companyInvitationsAcceptHandler.ts
src/routers/handlers/yourCompanies/companyInvitationsDeclineHandler.ts
src/views/partials/customer_insights.njk
test/src/routers/controllers/companyInvitationsAcceptController.test.ts
test/src/routers/controllers/companyInvitationsDeclineController.test.ts
test/src/routers/controllers/yourCompaniesController.addCompany.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1415
Changes:
- Updated 'Tell us what you think of this service' link
- Auto-formatting changes

IDVA6-1415 - Update "Tell us what you think of this service" Link

---

src/routers/handlers/yourCompanies/companyInvitationsAcceptHandler.ts
src/routers/handlers/yourCompanies/companyInvitationsDeclineHandler.ts
src/routers/handlers/yourCompanies/manageAuthorisedPeopleHandler.ts
test/src/routers/controllers/companyInvitationsAcceptController.test.ts
test/src/routers/controllers/companyInvitationsDeclineController.test.ts
test/src/routers/controllers/yourCompaniesController.addCompany.test.ts
test/src/routers/controllers/yourCompaniesController.test.ts

- Fixing linting issues outlined in https://ci-platform.companieshouse.gov.uk/teams/team-development/pipelines/your-companies-web/jobs/analyse-pull-request/builds/336#L66ba9fa8:47

BAU: Fix linting errors

---

package-lock.json

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1568
Changes:
- Fix for some of the vulnerabilities in dependencies

IDVA6-1568 Fix for vulnerabilities in dependencies

---

src/routers/controllers/httpErrorController.ts
src/views/layouts/default.njk
src/views/manage-authorised-people.njk
src/views/no-companies-added.njk
src/views/previously-added-companies.njk
src/views/your-companies.njk

https://companieshouse.atlassian.net/browse/IDVA6-1554
This PR add back the tracking of two goals for the following journeys: 
- Add a company
- Add an authorised user

IDVA6-1554 add function to track matomo goals

---

src/routerDispatch.ts
src/routers/handlers/yourCompanies/yourCompaniesHandler.ts
test/src/app.test.ts
test/src/lib/helpers/buildPaginationHelper.test.ts
test/src/lib/utils/referrerUtils.test.ts
test/src/routerDispatch.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1466
Changes:
- Unit tests refactored and new added
- Unused import removed
- Code reformatted

IDVA6-1466 refactoring

---

src/app.ts
src/lib/utils/error_manifests/errorManifest.ts
src/lib/utils/urlUtils.ts
src/middleware/navigation/addPresenter.middleware.ts
src/middleware/navigation/cancelPerson.middleware.ts
src/middleware/navigation/removeAuthorisedPerson.middleware.ts
src/routerDispatch.ts
src/routers/controllers/confirmCompanyController.ts
src/routers/controllers/httpErrorController.ts
src/routers/handlers/yourCompanies/addCompanyHandler.ts
src/routers/handlers/yourCompanies/addPresenterHandler.ts
src/routers/handlers/yourCompanies/cancelPersonHandler.ts
src/routers/handlers/yourCompanies/checkPresenterHandler.ts
src/routers/handlers/yourCompanies/companyAddSuccessHandler.ts
src/routers/handlers/yourCompanies/companyInvitationsAcceptHandler.ts
src/routers/handlers/yourCompanies/companyInvitationsDeclineHandler.ts
src/routers/handlers/yourCompanies/companyInvitationsHandler.ts
src/routers/handlers/yourCompanies/manageAuthorisedPeopleHandler.ts
src/routers/handlers/yourCompanies/presenterAlreadyAddedHandler.ts
src/routers/handlers/yourCompanies/removeAuthorisedPersonHandler.ts
src/routers/handlers/yourCompanies/removeThemselvesConfirmationHandler.ts
src/routers/handlers/yourCompanies/yourCompaniesHandler.ts
src/types/@types/express/index.d.ts
test/src/lib/utils/sessionUtils.test.ts
test/src/lib/utils/urlUtils.test.ts
test/src/services/companyProfileService.test.ts
tsconfig.json

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1466
Changes:
- Lang property added to Request interface of Express to remove type casting to any across the codebase
- Type any replaced with unknown
- Unused error messages removed
- Duplicated complex condition replaced with a function

IDVA6-1466 refactoring3

---

src/middleware/content.security.policy.middleware.config.ts
src/views/partials/__styles.njk

https://companieshouse.atlassian.net/browse/IDVA6-1625
**Changes**
- Updates style tag to include a nonce, 
- Allow scripts from source

IDVA6-1625 Update content security policy 

---

locales/cy/cancel-person.json
locales/cy/common.json
locales/cy/company-invitations.json
locales/cy/manage-authorised-people.json
locales/cy/your-companies.json
locales/en/cancel-person.json
locales/en/common.json
locales/en/company-invitations.json
locales/en/manage-authorised-people.json
locales/en/your-companies.json
package-lock.json
package.json
src/routers/handlers/yourCompanies/companyInvitationsHandler.ts
src/views/add-company.njk
src/views/add-presenter-check-details.njk
src/views/add-presenter.njk
src/views/cancel-person.njk
src/views/company-invitations.njk
src/views/manage-authorised-people.njk
src/views/partials/__header.njk
src/views/partials/back_link.njk
src/views/partials/customer_insights.njk
src/views/previously-added-companies.njk

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1352
Changes:
- Updated aria labels and visually hidden text for English and Welsh language files

IDVA6-1352 - Check and fix Your Companies Aria Labels

---

src/views/previously-added-companies.njk

Link to bug ticket:
https://companieshouse.atlassian.net/browse/IDVA6-1676
**Changes made:**
Adding styling such as column widths and paddings to add more spaces
**Before:**
**After:**

IDVA6-1676:Bug Fix Adding Space To Table Column

---

package-lock.json
package.json
src/views/partials/nav/top.njk

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1490
Changes:
- ch-node-utils updated to the newest version that includes code setting up displayAuthorisedAgent flag for the navbar
- displayAuthorisedAgent argument added to the navbar macro call

IDVA6-1490 modify navbar to conditionally show authorised agent

---

package-lock.json
package.json

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1629
Changes:
- web-security-node package bumped to the newest version

IDVA6-1629 Implement CSRF tokens

---

Makefile

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1843
Changes:
Test added to sonar prior to run sunarqube to fix problem with statistics not displayed for main branch

IDVA6-1843 Fix to SonarQube not showing statistics for main branch

---

locales/cy/remove-company.json
locales/en/remove-company.json
src/constants.ts
src/lib/utils/sessionUtils.ts
src/middleware/navigation/confirmationCompanyRemoved.middleware.ts
src/middleware/navigation/removeCompany.middleware.ts
src/routers/handlers/yourCompanies/removeCompanyConfirmedHandler.ts
src/routers/handlers/yourCompanies/removeCompanyHandler.ts
src/routers/handlers/yourCompanies/yourCompaniesHandler.ts
src/routers/router.ts
src/views/remove-company.njk
test/src/lib/utils/sessionUtils.test.ts
test/src/routers/controllers/removeCompanyConfirmedController.test.ts
test/src/routers/controllers/removeCompanyController.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1855
Changes:
- Updated incorrect page title for removeCompany page
- Fixed bug to allow for language to be switched on confirmationCompanyRemoved page
- Added redirection functionality for removeCompany and confirmationCompanyRemoved pages
- Fixed bug that removed removeCompany page errors when switching languages

IDVA6-1855 - Your Companies bugs from e2e

---

src/views/previously-added-companies.njk

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1877
Changes:
- Removed unnecessary custom styling that was causing console error

IDVA6-1877 - Bug fix - Investigate and resolve console errors in cidev

---

package-lock.json
package.json
src/app.ts
src/views/partials/nav/top.njk

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1950
Changes:
- ch-node-utils package updated to use newest version of the navbar common component
- Nunjucks global variable added to display your companies menu item in the navbar

IDVA6-1950 update ch node utils package version

---

package-lock.json

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1984
Changes:
- Vulnerable dependency fixed

IDVA6-1984 Vulnerability in dependencies fixed

---

src/routers/controllers/checkPresenterController.ts
src/routers/controllers/companyInvitationsAcceptController.ts
src/routers/controllers/companyInvitationsDeclineController.ts
src/routers/handlers/yourCompanies/removeCompanyHandler.ts
test/src/routers/controllers/removeCompanyController.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-2055
Changes:
- Code smells as indicated by SonarQube removed

IDVA6-2055 Remove code smells as indicated by SonarQube

---

jest.config.ts
src/app.ts
src/middleware/csrf.protection.middleware.ts
test/src/middleware/csrf.middleware.test.ts

**JIRA link**
https://companieshouse.atlassian.net/browse/IDVA6-2091
**Change description**
Adds whitelist for the CSRF middleware to ignore health check requests
Updates jest.config to remove coverageProvider: "v8" setting, which corrects the code coverage report

IDVA6-2091 add health check exception to CSRF middleware

---

package-lock.json
tools/seed-mongodb/README.md
tools/seed-mongodb/config.js
tools/seed-mongodb/functions/createAssociation.js
tools/seed-mongodb/functions/createAssociationsData.js
tools/seed-mongodb/functions/createAuthCodes.js
tools/seed-mongodb/functions/createCompaniesData.js
tools/seed-mongodb/functions/createCompany.js
tools/seed-mongodb/functions/createUser.js
tools/seed-mongodb/functions/createUsersData.js
tools/seed-mongodb/index.js
tools/seed-mongodb/package-lock.json
tools/seed-mongodb/package.json

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-2289
Changes:
- Created an auto populate data script for your-companies for all 3 dev environments

IDVA6-2289 - Auto populate data script - Your Companies

---

src/lib/helpers/buildPaginationHelper.ts
src/middleware/navigation/checkPresenter.middleware.ts
src/middleware/navigation/presenterAlreadyAdded.middleware.ts
src/routers/controllers/checkPresenterController.ts
src/routers/controllers/presenterAlreadyAddedController.ts
src/routers/handlers/yourCompanies/companyInvitationsHandler.ts
src/routers/handlers/yourCompanies/removeAuthorisedPersonHandler.ts
src/services/associationsService.ts
src/services/companyProfileService.ts
test/unit/src/services/associationsService.createAssociation.test.ts
test/unit/src/services/associationsService.getCompanyAssociations.test.ts
test/unit/src/services/associationsService.getUserAssociations.test.ts
test/unit/src/services/associationsService.updateAssociationStatus.test.ts
test/unit/src/services/companyProfileService.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-2339
Changes:
- Fixes to issues indicated by SonarQube

IDVA6-2339 Fixes to issues indicated by SonarQube

---

test/mocks/associations.mock.ts
test/unit/src/routers/handlers/yourCompanies/companyInvitationsDeclineHandler.test.ts
test/unit/src/routers/handlers/yourCompanies/companyInvitationsHandler.test.ts
test/unit/src/routers/handlers/yourCompanies/confirmCorrectCompanyHandler.test.ts
test/unit/src/routers/handlers/yourCompanies/manageAuthorisedPeopleHandler.test.ts
test/unit/src/routers/handlers/yourCompanies/presenterAlreadyAddedHandler.test.ts
test/unit/src/routers/handlers/yourCompanies/removeAuthorisedPersonHandler.test.ts
test/unit/src/routers/handlers/yourCompanies/removeCompanyConfirmedHandler.test.ts
test/unit/src/routers/handlers/yourCompanies/removeCompanyHandler.test.ts
test/unit/src/routers/handlers/yourCompanies/removeThemselvesConfirmationHandler.test.ts
test/unit/src/routers/handlers/yourCompanies/somethingWentWrongHandler.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-2271
Changes:
- Unit tests added

IDVA6-2271 adding new unit tests for handlers continuation

---

tools/seed-mongodb/README.md
tools/seed-mongodb/config.js
tools/seed-mongodb/functions/createUser.js

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-2394
Changes:
- Email provider config added to test data generator

IDVA6-2394 Email provider config added to test data generator

---

src/types/associations.ts
test/unit/src/routers/handlers/yourCompanies/yourCompaniesHandler.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-2271
Changes:
- Added unit tests for yourCompaniesHandler

IDVA6-2271 - Unit Test Refactoring - yourCompaniesHandler

---

package-lock.json
package.json
src/services/associationsService.ts
test/unit/src/services/associationsService.createAssociation.test.ts
test/unit/src/services/associationsService.postInvitation.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-2393
Changes:
- private-api-sdk-node updated to the newest version
- Code and tests updated to incorporate the changes from private-api-sdk-node

IDVA6-2393 wrong response from associations service

---

package-lock.json
package.json
src/app.ts
src/views/partials/nav/top.njk
test/unit/src/lib/utils/urlUtils.test.ts

https://companieshouse.atlassian.net/browse/IDVA6-2426
- Updates predefined navbar (nunjucks macro) with the account base url
- Updates ch-node-utils to version 1.3.23

IDVA6 2426 update navbar link 

---

nodemon.json
package-lock.json
package.json
src/bin/nodemon-entry.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-2450
Changes:
- Added relevant nodemon files as outlined in troubleshooting documentation
- Updated package json with relevant lines

IDVA6-2450 - Configuring Nodemon for Your Companies Web

---

package-lock.json

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-2458
Changes:
- Fix to vulnerabilities in dependencies

IDVA6-2458 Fix to vulnerabilities in dependencies

---

src/constants.ts
src/lib/utils/sessionUtils.ts
src/services/apiCallRetryService.ts
src/services/apiClientService.ts
src/services/associationsService.ts
src/services/refreshTokenService.ts
test/mocks/session.mock.ts
test/unit/src/lib/utils/sessionUtils.test.ts
test/unit/src/services/apiClientService.test.ts
test/unit/src/services/associationsService.getInvitations.test.ts
test/unit/src/services/refreshTokenService.test.ts
tsconfig.json

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-2446
https://companieshouse.atlassian.net/browse/IDVA6-2469
Changes:
- API call with retry functionality added and code refactored to use it
- Parameters to the function creating API client changed to fix the 500 bug

IDVA6-2446 change api call method to use call with retry

---

tools/seed-mongodb/functions/createCompany.js

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-2485
Changes:
- Company number format fixed

IDVA6-2485 Company number format fixed

---

package-lock.json
package.json

Bump node-session-handler version to 5.2.4

Bump node-session-handler version to 5.2.4

---

src/constants.ts
src/routers/handlers/yourCompanies/manageAuthorisedPeopleHandler.ts
src/routers/handlers/yourCompanies/yourCompaniesHandler.ts
src/views/manage-authorised-people.njk
src/views/partials/digital_authorisation_banner.njk
test/unit/src/routers/handlers/yourCompanies/manageAuthorisedPeopleHandler.test.ts
test/unit/src/routers/handlers/yourCompanies/yourCompaniesHandler.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/SIV-416
Changes:
- Updated authentication code information links on banners and remove confirmation page
- Set 'Not provided' to default value for all users without display names

SIV-416 - Bug Fix - Your Companies

---

assets/src/scss/partials/_nav.scss
src/routers/handlers/yourCompanies/addPresenterHandler.ts
src/views/layouts/default.njk
src/views/layouts/shell.njk
src/views/partials/__header.njk

Link to Jira:
https://companieshouse.atlassian.net/browse/SIV-417
Changes:
- Removed navigation wrapper around 'Skip to main content' link
- Converted 'Add person' user email to lower case to prevent multi-case profiles being created
- Ensured 'Tell us what you think' link opens in the same window

SIV-417 - Your Companies Improvements

---

src/middleware/navigation.middleware.config.ts
src/routers/controllers/createCompanyAssociationController.ts
src/routers/controllers/tryRestoringYourDigitalAuthorisationController.ts
test/unit/src/middleware/navigation.middleware.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/SIV-433
Changes:
- Fixes to bugs in restore your digital authorisation and add a company journeys

SIV-433 Bug fix for SIV-374

---

src/middleware/navigation.middleware.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/SIV-433
Changes:
- Additional logs added to aid debugging

SIV-433 Bug fix for SIV-374 - additional logs

---

locales/cy/manage-authorised-people.json
locales/en/manage-authorised-people.json
src/views/confirmation-authorisation-removed.njk
src/views/confirmation-company-removed.njk
src/views/manage-authorised-people.njk
src/views/partials/nav/top.njk
src/views/previously-added-companies.njk
src/views/remove-authorisation-do-not-restore.njk
src/views/remove-authorised-person.njk
src/views/remove-company.njk
src/views/remove-do-not-restore.njk
src/views/your-companies.njk

https://companieshouse.atlassian.net/browse/SIV-392
Adds tracking for new journeys
Adds missing data-event-ids for some missed pages / buttons.

SIV-392 Matomo: Track missing pages, buttons and links

---

package-lock.json
package.json
src/constants.ts
src/routers/controllers/resendEmailController.ts
src/services/apiClientService.ts
src/services/associationsService.ts
src/services/companyProfileService.ts
test/integration/your-companies/manage-authorised-people-email-resent/userEmail/get.test.ts
test/unit/src/routers/controllers/resendEmailController.test.ts
test/unit/src/services/associationsService.inviteUser.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/SIV-478
Changes:
- api-sdk-node dependency updated to the newest version
- code refactored to used the updated dependency

SIV-478 downstream lb changes using updated api client

---

package-lock.json

Link to Jira:
https://companieshouse.atlassian.net/browse/SIV-498
Changes:
- A critical vulnerability in dependencies fixed

SIV-498 Fix to a critical vulnerability in dependencies

---

src/constants.ts
src/routers/handlers/yourCompanies/yourCompaniesHandler.ts
test/unit/src/routers/handlers/yourCompanies/yourCompaniesHandler.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/SIV-496
Changes:
- Updated company information link to function in other environments

SIV-496 - Link Company Name to Register

---

src/views/manage-authorised-people.njk

https://companieshouse.atlassian.net/browse/SIV-448
Updates the CSS classes used for email input on the search on ‘People digitally authorised to file online for this company’ page.
This improves the display of this form on mobile.

SIV-448 Update inputs to include CSS classes for displaying on mobile

---

src/routers/handlers/yourCompanies/addCompanyHandler.ts
src/services/companyProfileService.ts
test/integration/your-companies/add-company/get.test.ts
test/integration/your-companies/add-company/post.test.ts
test/unit/src/routers/handlers/yourCompanies/addCompanyHandler.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/SIV-549
Changes:
- Error type changed so the http status could be passed to the catch clause

SIV-549 Correct error message not displayed

---

locales/cy/your-companies.json
locales/en/your-companies.json
src/routers/handlers/yourCompanies/yourCompaniesHandler.ts
src/views/previously-added-companies.njk
test/unit/src/routers/handlers/yourCompanies/yourCompaniesHandler.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/SIV-497
Changes:
- Company status added to the summary card on your companies page
- Language files sorted alphabetically

SIV-497 Company status added to the summary card

---

src/middleware/content.security.policy.middleware.config.ts

**Jira**
https://companieshouse.atlassian.net/browse/SIV-645
The content security policy was allowing form submissions to any url for debugging, this PR reverts that change.

SIV-645 remove allowing form submissions to any url

---

src/lib/utils/sessionUtils.ts
src/routers/controllers/removeAuthorisedPersonController.ts
src/routers/handlers/yourCompanies/confirmationAuthorisationEmailResentHandler.ts
src/routers/handlers/yourCompanies/sendEmailToBeDigitallyAuthorisedHandler.ts
src/routers/handlers/yourCompanies/yourCompaniesHandler.ts
test/unit/src/lib/utils/sessionUtils.test.ts
test/unit/src/routers/handlers/yourCompanies/confirmationAuthorisationEmailResentHandler.test.ts
test/unit/src/routers/handlers/yourCompanies/sendEmailToBeDigitallyAuthorisedHandler.test.ts
test/unit/src/routers/handlers/yourCompanies/yourCompaniesHandler.test.ts

https://companieshouse.atlassian.net/browse/SIV-601
Clears all search email strings on the various manage user page when user visits the your-companies page

SIV-601 search results remain after leaving page

---

src/middleware/content.security.policy.middleware.config.ts

https://companieshouse.atlassian.net/browse/SIV-707
Allows form to submit to any url.

SIV-707 update content security policy - allow all form submissions

---

src/app.ts

https://companieshouse.atlassian.net/browse/SIV-750
request-specific variables should be set using res.locals

SIV-750 move global nunjucks values to res.locals

---

README.md

Link to Jira:
https://companieshouse.atlassian.net/browse/SIV-682
Changes:
- Updated Your Companies README file

SIV-682 - Update README- Your Companies

---

src/services/associationsService.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/SIV-827
Changes:
- Removed sdk resource condition from 404 response statement

SIV-827 - Your Companies - Manage Users Search Bar Error

---

src/views/manage-authorised-people.njk
test/integration/your-companies/manage-authorised-people/companyNumber/get.test.ts
test/integration/your-companies/manage-authorised-people/companyNumber/post.test.ts
tools/seed-mongodb/functions/createUser.js

Link to Jira:
https://companieshouse.atlassian.net/browse/SIV-837
Changes:
- Display name removed from the manage authorised people template
- Display name removed from test data generator

SIV-837 remove display name
